apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-listener
  labels:
    app: event-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-listener
  template:
    metadata:
      labels:
        app: event-listener
    spec:
      containers:
        - name: event-listener
          image: quay.io/kmamgain/cdevent:latest
          imagePullPolicy: Always
          ports:
            - name: event-listener
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: event-listener
  name: event-listener
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: event-listener