apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-goodbye-run
spec:
  pipelineRef:
    resolver: git
    name: hello-goodbye
  params:
  - name: username
    value: "Tekton"
  - name: url
    value: ${REPO_URL}