kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: tekton-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: tekton-role
  apiGroup: rbac.authorization.k8s.io