apiVersion: v1
kind: Service
metadata:
  labels:
    app: event-listener
  name: event-listener
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: event-listener